export const enum GRAMMAR_SYMB {
	END_OF_FILE = 1,
	IDENTIFIER,
	FUNCTION,
	TYPE,
	TYPE_REF,
	STRING,
	JUSTAPOSING_COMBINATOR,
	AMPERSAND_COMBINATOR,
	DOUBLE_VERTICAL_COMBINATOR,
	SINGLE_VERTICAL_COMBINATOR,
	OPEN_SQUARE_BRACKET,
	SHUT_SQUARE_BRACKET,
	MULTIPLIER,
	RANGE,
}
export const enum GRAMMAR_TYPE {
	END_OF_FILE = 'SyntaxEndOfFile',
	IDENTIFIER = 'SyntaxIdentifier',
	FUNCTION = 'SyntaxFunction',
	TYPE = 'SyntaxType',
	TYPE_REF = 'SyntaxReferenceType',
	STRING = 'SyntaxString',
	JUSTAPOSING_COMBINATOR = 'SyntaxJustaposingCombinator',
	AMPERSAND_COMBINATOR = 'SyntaxAmpersand',
	DOUBLE_VERTICAL_COMBINATOR = 'SyntaxDoubleVerticalLineCombinator',
	SINGLE_VERTICAL_COMBINATOR = 'SyntaxSingleVerticalLineCombinator',
	OPEN_SQUARE_BRACKET = 'SyntaxOpenGroup',
	SHUT_SQUARE_BRACKET = 'SyntaxShutGroup',
	MULTIPLIER = 'SyntaxMultiplier',
	RANGE = 'SyntaxRange',
}
