export const enum SyntaxKind {
	EndOfFile,
	AtKeyword,
	CDC,
	CDO,
	Colon,
	Comma,
	Comment,
	Delimiter,
	Number,
	Dimension,
	Percentage,
	Function,
	Hash,
	Identifier,
	Semi,
	OpenBrace,
	ShutBrace,
	OpenParen,
	ShutParen,
	OpenBracket,
	ShutBracket,
	String,
	Url,
	Space,
	// --- * ---
	AtRule,
	ComponentValue,
	Declaration,
	FunctionRule,
	PreservedTokens,
	QualifiedRule,
	SimpleBlock,
}
export const SyntaxKindText = {
	[SyntaxKind.EndOfFile]: 'EndOfFile',
	[SyntaxKind.AtKeyword]: 'AtKeyword',
	[SyntaxKind.CDC]: 'CDC',
	[SyntaxKind.CDO]: 'CDO',
	[SyntaxKind.Colon]: 'Colon',
	[SyntaxKind.Comma]: 'Comma',
	[SyntaxKind.Comment]: 'Comment',
	[SyntaxKind.Delimiter]: 'Delimiter',
	[SyntaxKind.Number]: 'Number',
	[SyntaxKind.Dimension]: 'Dimension',
	[SyntaxKind.Percentage]: 'Percentage',
	[SyntaxKind.Function]: 'Function',
	[SyntaxKind.Hash]: 'Hash',
	[SyntaxKind.Identifier]: 'Identifier',
	[SyntaxKind.Semi]: 'Semi',
	[SyntaxKind.OpenBrace]: 'OpenBrace',
	[SyntaxKind.ShutBrace]: 'ShutBrace',
	[SyntaxKind.OpenParen]: 'OpenParen',
	[SyntaxKind.ShutParen]: 'ShutParen',
	[SyntaxKind.OpenBracket]: 'OpenBracket',
	[SyntaxKind.ShutBracket]: 'ShutBracket',
	[SyntaxKind.String]: 'String',
	[SyntaxKind.Url]: 'Url',
	[SyntaxKind.Space]: 'Space',
}
export const SyntaxKindMirror = {
	[SyntaxKind.OpenBrace]: SyntaxKind.ShutBrace,
	[SyntaxKind.OpenParen]: SyntaxKind.ShutParen,
	[SyntaxKind.OpenBracket]: SyntaxKind.ShutBracket,
}
export const enum SyntaxFlags {
	None /* */ = 0,
	ParseError = 1 << 0,
}
export const enum SyntaxModifierFlags {
	None /*     */ = 0,
	Integer /*  */ = 1 << 0,
	Double /*   */ = 1 << 1,
	BadString /**/ = 1 << 2,
	BadUrl /*   */ = 1 << 3,
}
